### ISSUE TITLE
[Feature] Add support for saving and loading heal assignment presets

### ISSUE THREAD

**Issue by csundlof** [csundlof/ClassicHealAssignments#6]
## Intended behavior
The user should be able to create healing assignments presets that can be loaded/saved freely. These should be labeled by the user as part of the save process. This would allow the user to set up healing assignments for encounters later on in the raid.

Functionally, this includes adding support for saving and loading the state of all healing assignments, as well as adding graphical components for the saving and loading of states. The graphical components for saving state should be akin to a save button as well as a textbox for input, and the component for loading the state should be a container of clickable elements (e.g. scrollframe of buttons) that load the state associated with the element in the container.

## Out of scope
* Persisting presets through /reloads or log outs.
* Support for removing presets

**Comment by dspoerr** [comment]
I can do this.

**Comment by csundlof** [comment]
Assigned it to you @dspoerr, have fun!

**Comment by csundlof** [comment]
Closed by #11
